package com.kds.backend.clubtypeconfig.application;
public enum Permission { ROLES_READ, ROLES_MANAGE, MEMBERS_READ, MEMBERS_WRITE, CONTRIBUTIONS_READ, CONTRIBUTIONS_WRITE, MEETINGS_READ, MEETINGS_WRITE, VOTES_READ, VOTES_CREATE, VOTES_CAST, DOCUMENTS_READ, DOCUMENTS_MANAGE, AUDIT_READ, REPORTS_READ }

