import { useState, type FormEvent } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { errorMessage } from "@/features/auth/auth-api"
import { EmptyState } from "@/components/states/EmptyState"
import { FolderOpen } from "lucide-react"
import { downloadDocument,useReplaceDocument,useUpdateDocument,type ClubDocument,type RoleOption } from "./document-hooks"

function size(value:number){return value<1024?`${value} B`:value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(1)} MB`}
function DocumentCard({document,roles,canManage}:{document:ClubDocument;roles:RoleOption[];canManage:boolean}){
  const update=useUpdateDocument();const replace=useReplaceDocument();const [editing,setEditing]=useState(false);const [title,setTitle]=useState(document.title);const [category,setCategory]=useState(document.category);const [selected,setSelected]=useState(document.visibleRoleCodes);const [replacement,setReplacement]=useState<File|null>(null);const [downloadError,setDownloadError]=useState("")
  const save=(event:FormEvent)=>{event.preventDefault();if(selected.length===0)return;update.mutate({id:document.id,metadata:{version:document.version,title,category,visibleRoleCodes:selected}},{onSuccess:()=>setEditing(false)})}
  return <article className="space-y-3 rounded-xl border bg-card p-4">
    <div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{document.title}</h3><p className="text-sm text-muted-foreground">{document.category} · updated {new Date(document.updatedAt).toLocaleString()}</p></div>{canManage&&!editing&&<Button type="button" variant="outline" onClick={()=>setEditing(true)}>Edit access</Button>}</div>
    {editing&&<form className="space-y-2" onSubmit={save}><label>Title<Input value={title} required onChange={event=>setTitle(event.target.value)}/></label><label>Category<Input value={category} required onChange={event=>setCategory(event.target.value)}/></label><fieldset><legend>Visible to roles</legend><div className="flex flex-wrap gap-3">{roles.map(role=><label className="flex gap-2" key={role.code}><input type="checkbox" checked={selected.includes(role.code)} onChange={event=>setSelected(current=>event.target.checked?[...current,role.code]:current.filter(code=>code!==role.code))}/>{role.name}</label>)}</div></fieldset>{selected.length===0&&<p role="alert">Select at least one role.</p>}{update.error&&<p role="alert">{errorMessage(update.error)}</p>}<div className="flex gap-2"><Button type="submit" disabled={update.isPending||selected.length===0}>Save</Button><Button type="button" variant="outline" onClick={()=>setEditing(false)}>Cancel</Button></div></form>}
    <div><h4 className="font-medium">Version history</h4><ol className="space-y-2">{document.versions.map(version=><li className="flex flex-wrap items-center justify-between gap-2 border-t pt-2" key={version.id}><span>v{version.versionNumber} · {version.fileName} · {size(version.fileSize)} · {new Date(version.uploadedAt).toLocaleString()}</span><Button type="button" variant="outline" onClick={()=>{setDownloadError("");void downloadDocument(document,version).catch(error=>setDownloadError(errorMessage(error)))}}>Download v{version.versionNumber}</Button></li>)}</ol></div>
    {downloadError&&<p role="alert">{downloadError}</p>}
    {canManage&&<div className="flex flex-wrap items-end gap-2"><label>Upload a new version<Input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.png,.jpg,.jpeg" onChange={event=>setReplacement(event.target.files?.[0]??null)}/></label><Button type="button" disabled={!replacement||replace.isPending} onClick={()=>replacement&&replace.mutate({id:document.id,version:document.version,file:replacement},{onSuccess:()=>setReplacement(null)})}>{replace.isPending?"Uploading…":"Add version"}</Button></div>}
    {replace.error&&<p role="alert">{errorMessage(replace.error)}</p>}
  </article>
}
export function DocumentLibrary({documents,roles,canManage}:{documents:ClubDocument[];roles:RoleOption[];canManage:boolean}){return <section className="space-y-3"><h2 className="text-xl font-semibold">Document library</h2>{documents.length===0?<EmptyState icon={FolderOpen} title="No documents are available yet" description={canManage?"Use the upload form above to share the club's first document and choose who may see it.":"Documents shared with your role will appear here."}/>:documents.map(document=><DocumentCard key={document.id} document={document} roles={roles} canManage={canManage}/>)}</section>}
