-- Global Investment Club configuration; tenant assignments remain on memberships.
CREATE TABLE permissions (code VARCHAR(60) PRIMARY KEY);
INSERT INTO permissions(code) VALUES ('ROLES_READ'), ('ROLES_MANAGE'), ('MEMBERS_READ'), ('MEMBERS_WRITE'), ('CONTRIBUTIONS_READ'), ('CONTRIBUTIONS_WRITE'), ('MEETINGS_READ'), ('MEETINGS_WRITE'), ('VOTES_READ'), ('VOTES_CREATE'), ('VOTES_CAST'), ('DOCUMENTS_READ'), ('DOCUMENTS_MANAGE'), ('AUDIT_READ'), ('REPORTS_READ');
CREATE TABLE roles (code VARCHAR(40) PRIMARY KEY, name VARCHAR(60) NOT NULL, club_type VARCHAR(40) NOT NULL);
INSERT INTO roles(code, name, club_type) VALUES ('ADMINISTRATOR', 'Administrator', 'INVESTMENT_CLUB'), ('CHAIRPERSON', 'Chairperson', 'INVESTMENT_CLUB'), ('TREASURER', 'Treasurer', 'INVESTMENT_CLUB'), ('SECRETARY', 'Secretary', 'INVESTMENT_CLUB'), ('MEMBER', 'Member', 'INVESTMENT_CLUB');
CREATE TABLE role_permissions (
 role_code VARCHAR(40) NOT NULL REFERENCES roles(code),
 permission_code VARCHAR(60) NOT NULL REFERENCES permissions(code),
 PRIMARY KEY(role_code, permission_code)
);
INSERT INTO role_permissions(role_code, permission_code) VALUES ('ADMINISTRATOR', 'ROLES_READ'), ('ADMINISTRATOR', 'ROLES_MANAGE'), ('ADMINISTRATOR', 'MEMBERS_READ'), ('ADMINISTRATOR', 'MEMBERS_WRITE'), ('ADMINISTRATOR', 'CONTRIBUTIONS_READ'), ('ADMINISTRATOR', 'CONTRIBUTIONS_WRITE'), ('ADMINISTRATOR', 'MEETINGS_READ'), ('ADMINISTRATOR', 'MEETINGS_WRITE'), ('ADMINISTRATOR', 'VOTES_READ'), ('ADMINISTRATOR', 'VOTES_CREATE'), ('ADMINISTRATOR', 'VOTES_CAST'), ('ADMINISTRATOR', 'DOCUMENTS_READ'), ('ADMINISTRATOR', 'DOCUMENTS_MANAGE'), ('ADMINISTRATOR', 'AUDIT_READ'), ('ADMINISTRATOR', 'REPORTS_READ'), ('CHAIRPERSON', 'ROLES_READ'), ('CHAIRPERSON', 'MEMBERS_READ'), ('CHAIRPERSON', 'MEETINGS_READ'), ('CHAIRPERSON', 'MEETINGS_WRITE'), ('CHAIRPERSON', 'VOTES_READ'), ('CHAIRPERSON', 'VOTES_CREATE'), ('CHAIRPERSON', 'VOTES_CAST'), ('CHAIRPERSON', 'DOCUMENTS_READ'), ('CHAIRPERSON', 'AUDIT_READ'), ('CHAIRPERSON', 'REPORTS_READ'), ('TREASURER', 'MEMBERS_READ'), ('TREASURER', 'CONTRIBUTIONS_READ'), ('TREASURER', 'CONTRIBUTIONS_WRITE'), ('TREASURER', 'MEETINGS_READ'), ('TREASURER', 'VOTES_READ'), ('TREASURER', 'VOTES_CAST'), ('TREASURER', 'DOCUMENTS_READ'), ('TREASURER', 'REPORTS_READ'), ('SECRETARY', 'MEMBERS_READ'), ('SECRETARY', 'MEMBERS_WRITE'), ('SECRETARY', 'MEETINGS_READ'), ('SECRETARY', 'MEETINGS_WRITE'), ('SECRETARY', 'VOTES_READ'), ('SECRETARY', 'VOTES_CAST'), ('SECRETARY', 'DOCUMENTS_READ'), ('SECRETARY', 'DOCUMENTS_MANAGE'), ('MEMBER', 'MEMBERS_READ'), ('MEMBER', 'CONTRIBUTIONS_READ'), ('MEMBER', 'MEETINGS_READ'), ('MEMBER', 'VOTES_READ'), ('MEMBER', 'VOTES_CAST'), ('MEMBER', 'DOCUMENTS_READ');
ALTER TABLE club_memberships ADD COLUMN role_code VARCHAR(40) NOT NULL DEFAULT 'MEMBER' REFERENCES roles(code);
UPDATE club_memberships SET role_code = 'ADMINISTRATOR' WHERE administrator = TRUE;
ALTER TABLE club_memberships DROP COLUMN administrator;

