import { fireEvent,render,screen,waitFor,within } from "@testing-library/react"
import { QueryClient,QueryClientProvider } from "@tanstack/react-query"
import { beforeEach,expect,it,vi } from "vitest"
import { useAuthStore } from "@/features/auth/auth-store"
import { MeetingsPage } from "./index"
const {get,post,put}=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),put:vi.fn()}))
vi.mock("@/features/auth/auth-api",()=>({api:{get,post,put},errorMessage:()=>"Meeting failed"}))
const upcoming={id:"meeting-1",version:0,title:"Committee meeting",description:"Club business",startsAt:"2026-10-03T10:00:00+02:00",durationMinutes:60,location:"Community hall",meetingUrl:null,agendaItems:[{id:"agenda-1",position:0,title:"Opening",description:null},{id:"agenda-2",position:1,title:"Finance",description:null}]}
beforeEach(()=>{vi.clearAllMocks();useAuthStore.getState().setSession("token",{id:"owner",email:"owner@example.test"},{id:"club",name:"Club",clubType:"INVESTMENT_CLUB",administrator:true,permissions:["MEETINGS_READ","MEETINGS_WRITE"]});get.mockImplementation((_path:string,config:{params:{view:string}})=>Promise.resolve({data:config.params.view==="UPCOMING"?[upcoming]:[]}));post.mockResolvedValue({data:upcoming});put.mockResolvedValue({data:{...upcoming,version:1}})})
function page(){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><MeetingsPage/></QueryClientProvider>)}
it("shows upcoming and past sections to read-only members",async()=>{useAuthStore.setState(state=>({activeClub:{...state.activeClub!,permissions:["MEETINGS_READ"]}}));page();expect(await screen.findByText("Committee meeting")).toBeInTheDocument();expect(screen.getByRole("heading",{name:"Past meetings"})).toBeInTheDocument();expect(screen.queryByRole("heading",{name:"Schedule a meeting"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Edit meeting"})).not.toBeInTheDocument()})
it("creates a meeting with agenda in the displayed order",async()=>{page();await screen.findByText("Committee meeting");fireEvent.change(screen.getByLabelText("Title"),{target:{value:"Annual meeting"}});fireEvent.change(screen.getByLabelText("Physical location"),{target:{value:"Main hall"}});fireEvent.change(screen.getByLabelText("Item 1 title"),{target:{value:"Welcome"}});fireEvent.click(screen.getByRole("button",{name:"Add agenda item"}));fireEvent.change(screen.getByLabelText("Item 2 title"),{target:{value:"Budget"}});fireEvent.click(screen.getByRole("button",{name:"Schedule meeting"}));await waitFor(()=>expect(post).toHaveBeenCalledWith("/meetings",expect.objectContaining({title:"Annual meeting",location:"Main hall",agendaItems:[expect.objectContaining({title:"Welcome"}),expect.objectContaining({title:"Budget"})]})))})
it("reorders the agenda and submits the optimistic version on edit",async()=>{page();fireEvent.click(await screen.findByRole("button",{name:"Edit meeting"}));const form=screen.getByRole("heading",{name:"Edit meeting"}).closest("form")!;const buttons=within(form).getAllByRole("button",{name:"Move up"});fireEvent.click(buttons[1]);fireEvent.click(within(form).getByRole("button",{name:"Save meeting"}));await waitFor(()=>expect(put).toHaveBeenCalledWith("/meetings/meeting-1",expect.objectContaining({version:0,agendaItems:[expect.objectContaining({title:"Finance"}),expect.objectContaining({title:"Opening"})]})))})
it("shows save failures without claiming success",async()=>{post.mockRejectedValue(new Error("offline"));page();await screen.findByText("Committee meeting");fireEvent.change(screen.getByLabelText("Title"),{target:{value:"Failed"}});fireEvent.change(screen.getByLabelText("Physical location"),{target:{value:"Hall"}});fireEvent.change(screen.getByLabelText("Item 1 title"),{target:{value:"Item"}});fireEvent.click(screen.getByRole("button",{name:"Schedule meeting"}));expect(await screen.findByRole("alert")).toHaveTextContent("Meeting failed")})
